### ISSUE TITLE
running file

### ISSUE THREAD

**Issue by yjydiancom** [abdulkadrtr/ROS2-PurePursuitControl-PathPlanning-Tracking#2]
Hi, I'm wondering if I'm following your instructions to run the code and find that none of the required files are available.
![2023-10-18 10-29-48 的屏幕截图](https://github.com/abdulkadrtr/ROS2-PurePursuitControl-PathPlanning-Tracking/assets/91858119/d71a3fa5-cb1c-48c6-89c4-03f613698b86)

**Comment by abdulkadrtr** [comment]
Hello, you need to download version 0.2.0 of the software. You can download the nav_controller.zip file at this address: https://github.com/abdulkadrtr/ROS2-PurePursuitControl-PathPlanning-Tracking/releases/tag/v.0.2.0. This repository does not contain the TurtleBot3 packages and the SLAM Toolbox packages. You can obtain these packages from the relevant repositories.
