### ISSUE TITLE
path planning in uneven terrain

### ISSUE THREAD

**Issue by yjydiancom** [abdulkadrtr/ROS2-PurePursuitControl-PathPlanning-Tracking#3]
Hi，Have you done any path planning in uneven terrain? Or adding height information to a 2D map for path planning? How do you get the height information of the surrounding terrain?

**Comment by abdulkadrtr** [comment]
Hi, I haven't developed a 3D route tracking package yet; however, this package is designed for mapping and navigation in environments with a flat surface. For a project like this, you should initially utilize 3D SLAM packages to map the environment, and then develop an algorithm for route planning on a 3D map.
